### ISSUE TITLE
RoomClimateControl exception

### ISSUE THREAD

**Issue by tuxianerDE** [stefan-kaestle/openhab2-addons#37]
I am getting for the Room Climate Control thing the following error when reading through the looks.

2020-08-15 15:02:33.676 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.Error: State request for service RoomClimateControl of device hdm:HomeMaticIP:3014F711A000239A18595A2C failed with status code 404 and error code ENTITY_NOT_FOUND
        at org.openhab.binding.boschshc.internal.BoschSHCBridgeHandler.getState(BoschSHCBridgeHandler.java:495) ~[?:?]
        at org.openhab.binding.boschshc.internal.services.BoschSHCService.refreshState(BoschSHCService.java:108) ~[?:?]
        at org.openhab.binding.boschshc.internal.BoschSHCHandler.handleCommand(BoschSHCHandler.java:124) ~[?:?]
        at org.openhab.binding.boschshc.internal.devices.climatecontrol.ClimateControlHandler.handleCommand(ClimateControlHandler.java:64) ~[?:?]
        at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:191) ~[?:?]
        at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_252]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_252]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

The thing configuration looks as follows:
//Fussbodenheizungs Thermostat
   Thing thermostat     flur            "Thermostat Flur" @ "Flur" [ id="hdm:HomeMaticIP:3014F711A000239A18595A2C"]
   Thing climate-control flur           "Thermostat Flur" @ "Flur" [ id="hdm:HomeMaticIP:3014F711A000239A18595A2C"]

The climate-control previously properly showed the "To be temperature" now it show -NaN as an exception occurs.

**Comment by tuxianerDE** [comment]
Ok so I updated and removed the thermostat piece. Dont see an error set temperature is reported as NULL as I am currently in summer mode. Would have expected 0 but I can handle that via a mapping, OR should we do that in the binding?

**Comment by coeing** [comment]
Just to have the information here as well, @tuxianerDE is using this device: https://www.bosch-smarthome.com/de/de/produkte/smart-system-solutions/raumthermostat

@tuxianerDE The NULL looks like the state is currently not initialized. That probably has to do with summer mode, any chance that you temporarily turn it off? Unfortunately I don't have this kind of device at home. The "climate-control" was meant to bind the virtual devices that the Bosch smart home system creates for each room a thermostat is in. These are the only devices where you can set the temperature, all other thermostats only deliver their current temperature (and other data like valve tappet position or humidity level). You device might need a binding for a "wall-thermostat" which is not implemented yet.
Please try to bind one of these devices with a "climate-control" binding instead to set your desired temperature:
```
2020-08-15 19:37:58.739 [INFO ] [chshc.internal.BoschSHCBridgeHandler] - Found device: name=-RoomClimateControl- id=roomClimateControl_hz_1
2020-08-15 19:37:58.747 [INFO ] [chshc.internal.BoschSHCBridgeHandler] - Found device: name=-RoomClimateControl- id=roomClimateControl_hz_3
```

**Comment by tuxianerDE** [comment]
Ok sure I can switch if off. Configuring this device as climate control shall I set the ID that is mentioned in the logs OR shall I set the devide ID I have obtained?

**Comment by coeing** [comment]
Please use the ID from the logs (i.e. roomClimateControl_hz_1 or roomClimateControl_hz_3). Those are no physical devices but virtual ones that are created by the Bosch smart home system.

**Comment by tuxianerDE** [comment]
ok changed it and now I can obtain the value (move one thing out of summer mode to see if it works).

Interesting enough they report not 5 degrees as set temp for summer mode, but that is probably what bosch tells the system too. One item that is note worthy, I had to restart openhap to get the old climate control thing replaced with the new value.
