### ISSUE TITLE
Exception logged when device is initialized

### ISSUE THREAD

**Issue by coeing** [stefan-kaestle/openhab2-addons#6]
Every time the binding is initialized (and with it the devices), I get an error inside the openhab.log:

```
2020-06-15 18:33:57.635 [WARN ] [chshc.internal.BoschSHCBridgeHandler] - refreshState: HTTP request failed: {}
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Concurrent Connect Timeout
	at org.eclipse.jetty.client.util.FutureResponseListener.getResult(FutureResponseListener.java:118) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:101) ~[?:?]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:685) ~[?:?]
	at org.openhab.binding.boschshc.internal.BoschSHCBridgeHandler.refreshState(BoschSHCBridgeHandler.java:525) ~[?:?]
	at org.openhab.binding.boschshc.internal.shuttercontrol.ShutterControlHandler.getDeviceState(ShutterControlHandler.java:106) ~[?:?]
	at org.openhab.binding.boschshc.internal.shuttercontrol.ShutterControlHandler.handleCommand(ShutterControlHandler.java:53) ~[?:?]
	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:191) ~[?:?]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.lambda$0(ThingLinkManager.java:267) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_232]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.net.SocketTimeoutException: Concurrent Connect Timeout
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:235) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector.access$1500(ManagedSelector.java:61) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:533) ~[?:?]
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:395) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:360) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:184) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918) ~[?:?]
	... 1 more
```

First question would be: Does it only happen for my Shutter Control device due to my ShutterControlHandler? Or is it a general problem?

**Comment by coeing** [comment]
@stefan-kaestle Would be nice if you could check if the exception is logged for you and another device as well :)

**Comment by Dfinity-skaestle** [comment]
I can have a look over the weekend I think :-)

**Comment by stefan-kaestle** [comment]
I can have a look over the weekend :-)

**Comment by coeing** [comment]
This exception didn't occur anymore for me, so I will close this issue. If anyone gets it, we can open it again with better steps to reproduce.
